# Generated by Django 4.1.1 on 2022-10-24 13:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_cartao', models.CharField(choices=[('F', 'Fisico'), ('D', 'Digital')], default='D', max_length=1)),
                ('numCartao', models.CharField(max_length=16)),
                ('vencimento_cartao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField(max_length=3)),
                ('celular', models.CharField(max_length=15)),
                ('data_nasc', models.DateField()),
                ('email', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('senha', models.IntegerField(validators=[django.core.validators.MinValueValidator(8, 'A senha precisa ter no minimo 8 caracteres')])),
                ('tipo', models.CharField(choices=[('F', 'Free'), ('P', 'Premium')], default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numConta', models.CharField(max_length=20)),
                ('agencia', models.CharField(max_length=5)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_emprestimo', models.CharField(choices=[('R', 'Recusado'), ('A', 'Aguardando'), ('C', 'Concluido')], default='A', max_length=1)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_solicitado', models.DateTimeField(auto_now_add=True)),
                ('taxa_juros', models.IntegerField(max_length=2)),
                ('qtd_parcelas', models.IntegerField(max_length=2)),
                ('valor_com_juros', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_primeira_parcela', models.DateTimeField(auto_now_add=True)),
                ('qtd_parcelas_pagas', models.IntegerField(max_length=2)),
                ('valor_total_pago', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup_bank.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transferencia', models.CharField(choices=[('P', 'Pix'), ('B', 'Boleto')], default='P', max_length=1)),
                ('valor_transferencia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('enviou_transf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviou_transf', to='setup_bank.usuario')),
                ('recebeu_transf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebeu_transf', to='setup_bank.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PgtoEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPgto', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_bank.emprestimos')),
            ],
        ),
        migrations.CreateModel(
            name='Faturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_fatura', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField()),
                ('vencimento_cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_bank.cartoes')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_extrato', models.CharField(choices=[('T', 'transferencia'), ('S', 'saque'), ('D', 'deposito')], default='S', max_length=1)),
                ('data_extrato', models.DateField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup_bank.conta')),
                ('transf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_bank.transferencia')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('numero', models.IntegerField(max_length=6, unique=True)),
                ('cep', models.IntegerField(max_length=9)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_bank.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cartoes',
            name='tipoClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_bank.usuario'),
        ),
    ]
