# Generated by Django 4.1.1 on 2022-10-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_bank', '0002_remove_endereco_bairro_remove_endereco_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo',
        ),
    ]
