# Generated by Django 4.1.1 on 2022-11-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_bank', '0004_cliente_endereco_delete_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='senha',
            field=models.CharField(max_length=8),
        ),
    ]
