# Generated by Django 4.1.1 on 2022-11-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_bank', '0005_alter_cliente_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_nasc',
            field=models.CharField(max_length=255),
        ),
    ]
