# Generated by Django 4.1.1 on 2022-11-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_bank', '0006_alter_cliente_data_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoes',
            name='tipoClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_bank.cliente'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='enviou_transf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviou_transf', to='setup_bank.cliente'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='recebeu_transf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebeu_transf', to='setup_bank.cliente'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
