# Generated by Django 4.1.3 on 2022-11-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_bank', '0008_remove_cartoes_numcartao_remove_cartoes_tipoclient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='data_primeira_parcela',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='data_solicitado',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='qtd_parcelas',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='qtd_parcelas_pagas',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='status_emprestimo',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='taxa_juros',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='valor_com_juros',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='valor_total_pago',
        ),
        migrations.DeleteModel(
            name='PgtoEmprestimo',
        ),
    ]
