# Generated by Django 4.1.3 on 2022-11-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_bank', '0009_remove_emprestimos_data_primeira_parcela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='senha',
            field=models.CharField(max_length=20),
        ),
    ]
