# Generated by Django 4.1.3 on 2022-11-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_bank', '0010_alter_cliente_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extrato',
        ),
    ]
