# Generated by Django 4.1.3 on 2022-11-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_bank', '0012_alter_transferencia_data_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='enviou_transf',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='recebeu_transf',
            field=models.CharField(max_length=255),
        ),
    ]
